# Generated by Django 3.1.5 on 2021-01-14 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_auto_20210114_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='response_time',
        ),
        migrations.AddField(
            model_name='engineer',
            name='total_response_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Total_Response Time'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='start_time',
            field=models.IntegerField(default=0),
        ),
    ]
