# Generated by Django 3.1.5 on 2021-04-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0033_procedure_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.equipment'),
        ),
    ]
