# Generated by Django 3.2.1 on 2021-05-19 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0034_alter_procedure_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='med.department'),
        ),
    ]
