# Generated by Django 3.1.5 on 2021-06-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0035_procedure_department'),
        ('med', '0034_auto_20210427_2354'),
    ]

    operations = [
    ]
